version: "3.2"
services:
  mango-database:
    image: mysql/mysql-server:latest
    container_name: mango-database
    network_mode: bridge
    volumes:
      - ./src/main/resources/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_DATABASE=mango_cms
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=
    ports:
      - "3306:3306"
    restart: on-failure
