server:
  error:
    include-message: always
jwt:
  secret: test
  issuer: Mango
  expire-duration: 2D
auth:
  cookie:
    is-http-only: false
    is-secure: false
    name: token
spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
    url: jdbc:mysql://172.17.0.2:3306/mango_cms?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=true&connectionTimeZone=Europe/Warsaw&serverTimezone=UTC&&useLegacyDatetimeCode=false
    username: user
    password: user
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  web:
    resources:
      static-locations: file:${storage.path}/${storage.assets-storage-configuration.path}
      add-mappings: true
  mvc:
    static-path-pattern: /assets/**
storage:
  path: /var/mangocms
  assets-storage-configuration:
    path: /